version: '3.3'
services:
  postgres:
  image: postgres:13
  environment:
   - POSTGRES_DB=biblioteca
   -  POSTGRES_USER=EMMA
   - POSTGRES_PASSWORD=3006
   ports:
   - 5432:5432
   volumes:
   - ./postgres_data:/var/lib/postgresql/data 